experimentName: MLP
searchSpaceFile: ./searchspace/MLP_searchspace.json
trialCommand: python MLP_main.py
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 7
maxTrialNumber: 100
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
assessor:
  name: Medianstop
  classArgs:
    optimize_mode: minimize
    start_step: 5
trainingService:
  platform: local
  useActiveGpu: True